import { Poppins } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/navbar/NavBar';

const font = Poppins({ 
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ["latin"] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <NavBar/>
        {children}
      </body>
    </html>
  );
}
